import { Router, type IRouter } from "express";
import { memoryCache } from "../lib/http-cache";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import sitesRouter from "./sites";
import pagesRouter from "./pages";
import postsRouter from "./posts";
import mediaRouter from "./media";
import usersRouter from "./users";
import taxonomyRouter from "./taxonomy";
import menusRouter from "./menus";
import formsRouter from "./forms";
import seoRouter from "./seo";
import aiRouter from "./ai";
import calendarRouter from "./calendar";
import pipelineRouter from "./pipeline";
import pluginsRouter from "./plugins";
import subscribersRouter from "./subscribers";
import postImagesRouter from "./post-images";
import broadcastRouter from "./broadcast";
import postCommentsRouter from "./post-comments";
import diagnosticsRouter from "./diagnostics";
import salesForceRouter from "./sales-force";
import cdOptimizerRouter from "./cd-optimizer";
import nexusFinanceRouter from "./nexus-finance";

const router: IRouter = Router();

// Short TTL cache for read-heavy tool endpoints
router.use("/nexus/cd-optimizer/metrics", memoryCache(15_000));
router.use("/cd-optimizer/metrics", memoryCache(15_000));
router.use("/nexus/cd-optimizer/health", memoryCache(30_000));
router.use("/nexus/finance/health", memoryCache(30_000));
router.use("/sales-force/pipeline", memoryCache(10_000));
router.use("/sales-force/agents", memoryCache(20_000));

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/dashboard", dashboardRouter);
router.use("/sites", sitesRouter);
router.use("/pages", pagesRouter);
router.use("/posts", postsRouter);
router.use("/posts/:id/images", postImagesRouter);
router.use("/posts/:id/broadcasts", broadcastRouter);
router.use("/posts/:id/comments", postCommentsRouter);
router.use("/media", mediaRouter);
router.use("/users", usersRouter);
router.use(taxonomyRouter);
router.use("/menus", menusRouter);
router.use("/forms", formsRouter);
router.use("/seo", seoRouter);
router.use("/ai", aiRouter);
router.use("/calendar", calendarRouter);
router.use("/pipeline", pipelineRouter);
router.use("/plugins", pluginsRouter);
router.use("/subscribers", subscribersRouter);
router.use("/diagnostics", diagnosticsRouter);
router.use("/sales-force", salesForceRouter);
router.use("/nexus/cd-optimizer", cdOptimizerRouter);
router.use("/cd-optimizer", cdOptimizerRouter);
router.use("/nexus/finance", nexusFinanceRouter);
router.use("/finance-intel", nexusFinanceRouter);

export default router;
